# ----- CLEO -----
# File: config.yaml
# Project: src
# Created Date: Monday 23rd June 2025
# Author: Clara Bayley (CB)
# Additional Contributors:
# -----
# Last Modified: Tuesday 1st July 2025
# Modified By: CB
# -----
# License: BSD 3-Clause "New" or "Revised" License
# https://opensource.org/licenses/BSD-3-Clause
# -----
# Copyright (c) 2023 MPI-M, Clara Bayley
# -----
# File Description:
# Configuration file for example of using CLEO's python bindings.
# Note: The initial superdroplets data read from file "initsupers_filename" can be made with
# CLEO's pySD module (see Python script "create_initsuperdropsbinary_script.py" for usage).
# Likewise the "grid_filename" can be made using pySD (see "create_gbxboundariesbinary_script.py").
#

### Python Binding Parameters ###
pycleo_setup:
  is_motion : true                      # true/false, if true include superdroplet motion in SDM

### Kokkos Initialization Parameters ###
kokkos_settings:
  num_threads : 16                      # number of threads for host parallel backend
  device_id :  0                        # device to use for device parallel backend
  map_device_id_by : random             # select device for execution, either "mpi_rank" or "random"

### SDM Runtime Parameters ###
domain:
  nspacedims : 2                        # no. of spatial dimensions to model
  ngbxs : 9                             # total number of Gbxs
  maxnsupers: 36                        # maximum number of SDs

timesteps:
  CONDTSTEP : 1                         # time between SD condensation [s]
  COLLTSTEP : 1                         # time between SD collision [s]
  MOTIONTSTEP : 1                       # time between SDM motion [s]
  COUPLTSTEP : 3                        # time between dynamic couplings [s]
  OBSTSTEP : 3                          # time between SDM observations [s]
  T_END : 10                            # time span of integration from 0s to T_END [s]

### Initialisation Parameters ###
inputfiles:
  constants_filename : ./build/_deps/cleo-src/libs/cleoconstants.hpp  # name of file for values of physical constants
  grid_filename : ./share/cleo_initial_conditions/generic/dimlessGBxboundaries.dat  # binary filename for initialisation of GBxs / GbxMaps

initsupers:
  type: frombinary                                              # type of initialisation of super-droplets
  initsupers_filename : ./share/cleo_initial_conditions/generic/dimlessSDsinit.dat  # binary filename for initialisation of SDs
  initnsupers: 24

### Output Parameters ###
outputdata:
  setup_filename : ./build/bin/setup.txt     # .txt filename to copy configuration to
  zarrbasedir : ./build/bin/sol.zarr  # zarr store base directory
  maxchunk : 2500000                         # maximum no. of elements in chunks of zarr store array

### Pycleo (Python Bindings) Parameters ###
pycleo:
  enable_terminal_velocity : true                                  # true enables terminal velocity in superdroplet motion
  enable_condensation : false                                      # true enables condensation in microphysics
  enable_collisions : false                                        # true enables collisions in microphysics
